### ISSUE TITLE
Deactivate Sync Now if vendor ID is invalid

### ISSUE THREAD

**Issue by odrobnik** [Cocoanetics/AutoIngest#10]
The default vendor ID is 8XXXXXXX. If this is not replaced with a 8-digit number that begins with an 8, then "sync now" should be disabled.

Currently you can push it and then you see "Stop Sync", but that never does anything.

**Comment by ricobeck** [comment]
that's correct. maybe there should also be an explanation where to find the vendor id.

does the preferences window open automatically during the first run?

**Comment by fcy** [comment]
An explanation is a good idea. I didn't know where to find it until recently.

Also wouldn't it be better to validate the field and not allow invalid values? Something like this regex `8\d{7}`

**Comment by ricobeck** [comment]
i think validation would be much better than failing. especially if it's that easy.

**Comment by odrobnik** [comment]
Yes, validate ALL THE FIELDS. I just don't know how to do that. Also, since there is no Save the app needs to also be able to deal if invalid values are saved.

**Comment by ricobeck** [comment]
ok. i going to implement this during the next couple of days. validation and linking the sync now enabled status with valid data.

**Comment by fcy** [comment]
Do both things would be best solution. Validate the field and instead of only disabling the `Sync Now` we could change it to a disable `Invalid Vendor ID`.

**Comment by odrobnik** [comment]
@ricobeck What's the status of your branch. Can I merge it in for today's release?

**Comment by ricobeck** [comment]
currently there is only checking implemented. one can still select synching from the menu without (formally) correct data. you can cherry pick it but it's not complete.

**Comment by odrobnik** [comment]
if I merged in your branch would I get any problems, or would I get the form validation?

**Comment by ricobeck** [comment]
i pulled from develop an merged it. you can check out this branch, test, and merge it into develop if everything works.

**Comment by odrobnik** [comment]
ok, I did that. But you still are stuck on Stop Sync if you push sync Now with no valid vendor ID. Maybe you could address this next?

**Comment by ricobeck** [comment]
when i said 'there is only checking implemented' i meant of course 'there is only validation when you are typing implemented'. the next step is disabling the menu item and display a short error message as menu title.

**Comment by odrobnik** [comment]
I'm thinking that it might be confusing to change the contents of the menu. Simply disabling "Sync Now" would be best.

And on app launch I would show the first page of preferences if setup is incomplete, same as clicking on Preferences. Or maybe we could do a sort of message or popover from the icon, saying something like "Setup an Apple ID and Vender ID in the Preferences" that when clicked opens the preferences?

**Comment by odrobnik** [comment]
Upon further research, the NSPopOver class is available since 10.7, so I think that this might be the ideal candidate for a sort of welcome screen. Have a XIB with the welcome text sort of like:

"Welcome to AutoIngest for Mac. This app runs in our status bar and automatically downloads your Sales reports from Apple to your hard disk. 

Setup an account with Apple ID and Vendor ID in Preferences to get started."

This would pop up on app launch if any or the fields does not validate.

**Comment by JanX2** [comment]
I have worked with NSPopOver while prototyping the new menu animation. I have to say that I could not get the frameworks to keep the menu icon highlighted while the NSPopOver is being displayed and simultaneously use the automatics effects for the icon.

**Comment by ricobeck** [comment]
despite of the fact that it is hard to implement i find it a little strange to have an initial popover and later a menu.

**Comment by odrobnik** [comment]
Ok, then I withdraw my idea. Just disable the sync now.

**Comment by JanX2** [comment]
> despite of the fact that it is hard to implement i find it a little strange to have an initial popover and later a menu.

Yeah. That, too!

**Comment by JanX2** [comment]
I have an alternative suggestion: what about a modal window animating to the its default location on the screen (as per Apple HIG) with a zoom effect starting at the icon? I just don’t know of an immediate way to get the frame of the icon now that I have implemented it using NSStatusItem’s own drawing.

**Comment by odrobnik** [comment]
I think a normal modal alert should do the trick.

**Comment by odrobnik** [comment]
@JanX2  Do you have something for me today? Friday is AutoIngest release day.

**Comment by odrobnik** [comment]
Fixed in 81f31aebc7c1bc17708d1bcbc0b30ab66fd3b1e8. @ricobeck had renamed the action method name but did not update the validateMenuItem to match.
