### ISSUE TITLE
OS X 10.7 Compatibility

### ISSUE THREAD

**Issue by odrobnik** [Cocoanetics/AutoIngest#12]
Is it possible to support OS X 10.7?

If yes, please see this issue as a feature request.

Autolayout, used in the XIBs, should not be a problem, right?

**Comment by fcy** [comment]
According to [Deploymate](www.deploymateapp.com) we only use `NSUserNotification` that is not available in 10.7. And all the 6 calls to it are in AppDelegate's `syncDidFinish:`

Looks doable. Does anyone have a 10.7 install to test? I don't.

**Comment by ricobeck** [comment]
i have a mac mini running lion at the office. a can test on monday.

**Comment by odrobnik** [comment]
So how about doing some availability checking for these cases. So that these only are called on 10.8. then we could reduce the deployment target.
