### ISSUE TITLE
Third Party Code

### ISSUE THREAD

**Issue by odrobnik** [Cocoanetics/AutoIngest#14]
This is to clarify usage of third party libraries. Please don't check in code into develop that you don't have the copyright for and are willing and able to assign it to Cocoanetics.

@JanX2 put in NoodleKit only for use of a helper method for NSTimer. And he did so right into develop.

I don't want this. Never add any third party code directly into develop. If you must put it in a branch for the other team members to review.

If it is functionality that would take more than 3 lines of code then make a project-local category or tell me to add it to DTFoundation.

Please help keep the project slim and understandable by others.

**Comment by JanX2** [comment]
OK. No problem. :)

Here is the link about Mr. Noodle’s rationale behind that code: http://www.noodlesoft.com/blog/2010/07/01/playing-with-nstimer/

It’s under a very permissive license. If you really think it’s necessary we can move this into wherever or reimplement it. I don’t like the resulting fragmentation, though: work on one version of the code doesn’t benefit others if you split it off. 

This way, for example, I could use an ARC-ready fork directly without having to ARCify the original code. I wouldn’t have been able to find it had it been in some other framework or source code collection like DTFoundation. 

I just don’t like reinventing the wheel unless there is some immediate advantage. You can always do that later on should your wheel turn out to be unfit for purpose.

**Comment by odrobnik** [comment]
I removed NoodleKit in 6cc5cde430a852b2002c07445d8ad878c8a2db69 and think my implementation is clearer to read, has less code and retains the same functionality.

I put the timer back to the 24 hour interval and for situations where the Mac sleeps there is NSWorkspaceDidWakeNotification.

@JanX2 There is a difference between reinventing a wheel and adding tons of unnecessary code when the actual goal can be achieved with a simple extra notification observation. Also the point of this rule is to only have code in this project that we ourselves have written and thus understand what it does and are able to reproduce it any time ourselves. 

Mr. Noodles is probably a very smart guy, but simply using methods that he put together does not teach us any new tricks. On the other hand, looking at his code just taught me about the NSWorkspaceDidWakeNotification. I consider this a valuable trick to have learned, which - relying on the helper methods in his NSTimer category - I wouldn't have.

**Comment by JanX2** [comment]
It’s your project. It’s your decision. 

BTW: What about the sync drift issue I commented on?

**Comment by odrobnik** [comment]
@JanX2 working on it, I just implemented Reachability (#15) and will do that next.

**Comment by odrobnik** [comment]
@JanX2 Fixed the "sync drift issue". Basically I changed the timer to be hourly and the _startAutoSyncIfNecessary checks if a sync is necessary based on the date components.

**Comment by JanX2** [comment]
That’s a reasonable solution!

**Comment by odrobnik** [comment]
I'm glad you agree. :-)
