### ISSUE TITLE
Changing account preferences causes exceptions

### ISSUE THREAD

**Issue by JanX2** [Cocoanetics/AutoIngest#2]
I just tried setting up AutoIngest. I immediately failed, because changing the account preferences results in exceptions:

```
An uncaught exception was raised
*** setObjectForKey: object cannot be nil (key: v_Data)
```

Additionally for mosts key pressed, two characters will appear. 

Should this be a difficult fix, I will do this myself.

**Comment by odrobnik** [comment]
@JanX2 I refactored the keychain access in GenericAccount a bit. I hope that this fixes it. If the password is empty I now encode a @"" and that seems to work.

**Comment by JanX2** [comment]
Thanks! That seems to have done the trick.
