### ISSUE TITLE
Menu Improvements No Longer Shows Menu

### ISSUE THREAD

**Issue by odrobnik** [Cocoanetics/AutoIngest#21]
Since the latest changes in #20 now the menu does no longer show.

**Comment by JanX2** [comment]
This is fixed in a8ae19088d3b72116275eb19af6a84a45095e9bf.

**Comment by odrobnik** [comment]
@JanX2 Where is this commit? I don't see it in the commits or the network?

**Comment by odrobnik** [comment]
Ah, now it appeared.

**Comment by odrobnik** [comment]
merged the fix into _develop_
