### ISSUE TITLE
Provide App Icon

### ISSUE THREAD

**Issue by odrobnik** [Cocoanetics/AutoIngest#22]
We need an app icon to replace the current Xcode default one.

I thought maybe a threedimensional Golden Apple that has a bite. The metaphor being that having an app on the app store should be like having a tree that produces golden apples. And the bite in combination with the Apple of course being a reference to Apple itself.

**Comment by JanX2** [comment]
Christian and I are working on this. May take a while, though.

**Comment by odrobnik** [comment]
@JanX2 Do you have something for me today? Friday is AutoIngest release day.

**Comment by odrobnik** [comment]
@JanX2 Since you didn't respond in time, I'm using the design you previously sent me.

**Comment by odrobnik** [comment]
Implemented in af38b86e21d69b70097427d23c6653df1b998caf
