### ISSUE TITLE
File Not Found - DTReachability.h

### ISSUE THREAD

**Issue by sikosis** [Cocoanetics/AutoIngest#24]
/AutoIngest-develop/AutoIngest/Source/DTITCReportManager.m:13:9: 'DTReachability.h' file not found

Any idea where I get this file from ? I did a search but didn't find anything ...

**Comment by odrobnik** [comment]
That is Part of DTFoundation submodule

**Comment by sikosis** [comment]
I couldn't find it in DTFoundation (https://github.com/Cocoanetics/DTFoundation) and if I try to import DTFoundation instead of DTReachability, it still brings back errors.

**Comment by odrobnik** [comment]
I found that I had forgotten to push a commit to the AutoIngest develop branch. That fixes that.
