### ISSUE TITLE
Problem if both unzipping and organizing

### ISSUE THREAD

**Issue by odrobnik** [Cocoanetics/AutoIngest#26]
If both unzipping and organizing post processing options are chosen, then some files might appear zipped in the organized structure.

The reason is that the files get written to the report folder before they get unzipped in place.

**Comment by fcy** [comment]
You warned me about this and I forgot

**Comment by odrobnik** [comment]
@fcy I already fixed it. But I'm thinking maybe it would be better to do the unzipping-management inside the organizer. So that we have a separation of concerns. The downloader would only put files into the download folder and the organizer would take care of all post-processing. What do you think?

**Comment by fcy** [comment]
I agree, refactor the unzipping outside the downloader is a good thing.
