### ISSUE TITLE
Support Multiple Vendor IDs

### ISSUE THREAD

**Issue by odrobnik** [Cocoanetics/AutoIngest#32]
I would like to be able to enter multiple vendor IDs in the vendor ID field, separated by colon. This should be saved as an array in the user defaults. On synching this would then instantiate a sync as configured for each vendor ID.

I'm thinking that this would be a great use for a token field. You know where upon completing a valid 8-digit vendor id it would turn into one "blue pill", like e-mail addresses in mail.app.

Who's up for that?

**Comment by fcy** [comment]
The "blue pill" is a nice idea (and a great name :). Sorry the delay I'm a bit without free time at the moment :(
