### ISSUE TITLE
Crash on sync with no internet connection

### ISSUE THREAD

**Issue by JanX2** [Cocoanetics/AutoIngest#33]
I just had a crash in “-syncDidFinish:”. It occurred when manually syncing right after waking from sleep. I was dropped right into Xcode/lldb. The previous message in the log was “NO Internet Connection”. 

I can’t seem to be able reproduce it at this moment, so I am just logging it here. Apparently, the sync menu item is usually gray out when there is no net. I could be a timing issue…

**Comment by odrobnik** [comment]
What's the crash report?

**Comment by JanX2** [comment]
I would love to dig up one, but it was lost once I tried to reproduce it. If I remember correctly, it crashed right on the first line of “-syncDidFinish:”, which is really weird.

**Comment by odrobnik** [comment]
I don't think that this was a real crash. NSURLConnection uses exceptions for flow internally and you caught this because you had the debugger attached.

**Comment by JanX2** [comment]
Ah. That’s a good possibility!
