### ISSUE TITLE
Implement Sparkle

### ISSUE THREAD

**Issue by ricobeck** [Cocoanetics/AutoIngest#4]
sparkle in its current binary distribution is not able to check developer signed apps. this is a very handy feature when you compare the affords to secure updates.
to enable it one has to use the latest version of its master branch. (see https://github.com/andymatuschak/Sparkle/wiki)
there are two options: add it as a submodule and make it a part of the build process or include it as a precompiled framework. both ways have there advantages. which one should we go?

**Comment by odrobnik** [comment]
I have done it twice before in Combination with Developer ID, see my writeup here: http://www.cocoanetics.com/2012/11/in-house-mac-app-distribution-with-sparkle/

I think I used the framework approach. Does that have a disadvantage in your opinion?

**Comment by odrobnik** [comment]
PS: the actual signing and building of the appcast xml I would do on our Jenkins CI server

**Comment by odrobnik** [comment]
Sparkle is now implemented, and I released version 0.3.0 with it: http://www.cocoanetics.com/2013/05/autoingest-for-mac-0-3-0/
