### ISSUE TITLE
Integrate New Animated Icon

### ISSUE THREAD

**Issue by odrobnik** [Cocoanetics/AutoIngest#8]
I added a new animated icon and included it as good as I could. Please have a look.

![AutoIngest_72px_with_Statusbar](https://f.cloud.github.com/assets/333270/422077/4d3ce54e-ad1a-11e2-814b-e699084849db.gif)

Is there a better way to get the black of the icon to show as white while the menu is showing? I could only think of an XOR but that does not come out as white as it should.

**Comment by odrobnik** [comment]
PS: I put that into the cocoanetics/new_status_icon branch. Please merge into develop if you approve.

**Comment by fcy** [comment]
I liked the icon!

**Comment by odrobnik** [comment]
Since I didn't get any answer here I went ahead and merged the branch. 

@ricobeck you are still welcome to look at the inverting of the icon when menu is open.

**Comment by ricobeck** [comment]
i was a little busy. maybe a can do some things during the upcoming weekend. sorry for the delay.
